"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/app-shell";
import {PageHead} from "@/components/page-head";

type Template={id:string,name:string,channel:"email"|"whatsapp",subject:string|null,body:string,active:boolean};
const blank:Template={id:"",name:"Novo template",channel:"email",subject:"",body:"Olá {{primeiro_nome}},\n\nGostaria de falar com quem cuida das compras da {{empresa}}.",active:true};
export default function Templates(){
 const[list,setList]=useState<Template[]>([]),[selected,setSelected]=useState<Template>(blank),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/templates",{cache:"no-store"});const j=await r.json();if(r.ok){setList(j.data||[]);if(j.data?.length)setSelected(j.data[0])}else setMsg(j.error);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(){setMsg("");const method=selected.id?"PUT":"POST";const r=await fetch("/api/templates",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(selected)});const j=await r.json();if(!r.ok){setMsg(j.error);return}setMsg("Template salvo.");await load();setSelected(j.data)}
 function novo(){setSelected({...blank})}
 return <AppShell><PageHead title="Templates" description="Parametrize mensagens sem alterar código" action={<button className="btn" onClick={novo}>+ Novo template</button>}/><div className="split"><section className="card panel"><h2>Biblioteca</h2>{loading?<div className="muted">Carregando...</div>:<div className="stack">{list.length===0&&<div className="empty">Nenhum template ainda.</div>}{list.map(t=><button key={t.id} className="btn secondary" style={{textAlign:"left"}} onClick={()=>setSelected(t)}>{t.name}<div className="muted">{t.channel.toUpperCase()} • {t.active?"Ativo":"Inativo"}</div></button>)}</div>}</section><section className="card panel"><h2>{selected.id?"Editar template":"Novo template"}</h2><div className="stack"><div className="field"><label>Nome</label><input className="input" value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></div><div className="field"><label>Canal</label><select className="select" value={selected.channel} onChange={e=>setSelected({...selected,channel:e.target.value as "email"|"whatsapp"})}><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option></select></div>{selected.channel==="email"&&<div className="field"><label>Assunto</label><input className="input" value={selected.subject||""} onChange={e=>setSelected({...selected,subject:e.target.value})}/></div>}<div className="field"><label>Mensagem</label><textarea className="textarea" value={selected.body} onChange={e=>setSelected({...selected,body:e.target.value})}/></div><label className="row"><input type="checkbox" checked={selected.active} onChange={e=>setSelected({...selected,active:e.target.checked})}/> Ativo</label><div className="notice">Variáveis: {"{{empresa}} {{primeiro_nome}} {{bairro}} {{segmento}} {{vendedor}}"}</div>{msg&&<div className="notice success">{msg}</div>}<div className="row"><button className="btn" onClick={save}>Salvar</button></div><div className="template-preview">{selected.subject&&<><b>Assunto: {selected.subject}</b>{"\n\n"}</>}{selected.body}</div></div></section></div></AppShell>
}
